
2019-05-24 14:13:53,357 [WARNING] Not Found: /favicon.ico
2019-05-24 15:21:39,898 [ERROR] Internal Server Error: /webapp/index/
Traceback (most recent call last):
  File "/home/cjb/Py1901/Env/webenv/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/cjb/Py1901/Env/webenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/cjb/Py1901/Env/webenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/cjb/Web/web/webmonitors/webapp/views.py", line 25, in index
    return render(request, 'webapp/index.html', {'sys_name': system_name, 'host_info_obj': host_info_obj})
  File "/home/cjb/Py1901/Env/webenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/cjb/Py1901/Env/webenv/local/lib/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/cjb/Py1901/Env/webenv/local/lib/python2.7/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/home/cjb/Py1901/Env/webenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/cjb/Py1901/Env/webenv/local/lib/python2.7/site-packages/django/template/engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "/home/cjb/Py1901/Env/webenv/local/lib/python2.7/site-packages/django/template/engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/home/cjb/Py1901/Env/webenv/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/cjb/Py1901/Env/webenv/local/lib/python2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/cjb/Py1901/Env/webenv/local/lib/python2.7/site-packages/django/template/base.py", line 230, in compile_nodelist
    return parser.parse()
  File "/home/cjb/Py1901/Env/webenv/local/lib/python2.7/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
TemplateSyntaxError: Could not parse the remainder: 'url']}}/{{result['num']}}_time.png'' from ''rrdtool/{{result['url']}}/{{result['num']}}_time.png''
2019-05-24 16:31:26,551 [WARNING] Not Found: /favicon.ico
